
function el(s,r=document){return r.querySelector(s)}; function els(s,r=document){return [...r.querySelectorAll(s)]};
const CFG = window.SD_SITE_CONFIG || {}; const DATA = window.SD_SITE_DATA || {};
function mountLayout(active=''){
  const items=[['corrugated.html','골판지박스'],['colorbox.html','칼라박스'],['rigid.html','싸바리박스'],['other.html','기타'],['portfolio.html','포트폴리오'],['support.html','고객지원'],['quote.html','견적문의'],['login.html','로그인']];
  document.body.insertAdjacentHTML('afterbegin', `<div class="top-banner"><span>박스 맞춤 인쇄, 패키지 제작 · 샘플부터 견적, 납품까지 한번에</span></div><header class="header"><div class="container header-inner"><a class="brand" href="index.html"><img src="assets/sd-company-logo.png" alt="로고"><span>에스디컴퍼니</span></a><nav class="nav">${items.map(([h,l])=>`<a href="${h}" class="${active===h?'active':''} ${l==='견적문의'?'cta':''}">${l}</a>`).join('')}</nav><div class="mobile-menu"><a class="btn line" href="quote.html">견적문의</a></div></div></header>`);
  document.body.insertAdjacentHTML('beforeend', `<footer class="footer"><div class="container footer-grid"><div><div class="brand" style="font-size:18px"><img src="assets/sd-company-logo.png" alt="logo"><span>${CFG.companyName}</span></div><p>${CFG.phone}</p><p>${CFG.inquiryEmail}</p><p>${CFG.website}</p></div><div><h4><a href="all-products.html">PRODUCTS</a></h4><a href="corrugated.html">골판지박스</a><a href="colorbox.html">칼라박스</a><a href="rigid.html">싸바리박스</a><a href="other.html">기타</a></div><div><h4><a href="portfolio.html">COMPANY</a></h4><a href="portfolio.html">포트폴리오</a><a href="why-sd.html">WHY SD</a><a href="customer-reviews.html">고객 후기</a><a href="support.html">고객지원</a></div><div><h4><a href="support.html">SERVICE</a></h4><a href="quote.html">견적문의</a><a href="guide-paper.html">종이 선택 가이드</a><a href="guide-process.html">제작 과정</a><a href="shape-recommendation.html">형태 추천</a></div><div><h4><a href="support.html">CONTACT</a></h4><p>상담 메일: ${CFG.inquiryEmail}</p><p>대표 전화: ${CFG.phone}</p><p>영업시간: 평일 09:00 - 18:00</p><p>사업장 주소: 경기도 김포시 통진읍 마송2로104번길 155</p></div></div></footer>`);
}
function productCard(p){ return `<article class="product-card"><div class="badge-top">${p.tag||''}</div><img src="${p.img}" alt="${p.name}"><div class="body"><div class="product-meta"><strong>${p.name}</strong><span>${p.minQty||''}</span></div></div></article>`; }
