
function el(s,r=document){return r.querySelector(s)}; function els(s,r=document){return [...r.querySelectorAll(s)]};
const CFG = window.SD_SITE_CONFIG || {}; const DATA = window.SD_SITE_DATA || {};
function mountLayout(active=''){
  const items=[['corrugated.html','골판지박스'],['colorbox.html','칼라박스'],['rigid.html','싸바리박스'],['other.html','기타'],['portfolio.html','포트폴리오'],['support.html','고객지원'],['quote.html','견적문의'],['login.html','로그인']];
  document.body.insertAdjacentHTML('afterbegin', `<div class="top-banner">에스디컴퍼니 스타일 맞춤 패키지 제작 · 샘플부터 견적까지 한 번에</div><header class="header"><div class="container header-inner"><a class="brand" href="index.html"><img src="assets/sd-company-logo.png" alt="로고"><span>에스디컴퍼니 스타일</span></a><nav class="nav">${items.map(([h,l])=>`<a href="${h}" class="${active===h?'active':''} ${l==='견적문의'?'cta':''}">${l}</a>`).join('')}</nav><div class="mobile-menu"><a class="btn line" href="quote.html">견적문의</a></div></div></header>`);
  document.body.insertAdjacentHTML('beforeend', `<footer class="footer"><div class="container footer-grid"><div><div class="brand" style="font-size:18px"><img src="assets/sd-company-logo.png"><span>${CFG.companyName}</span></div><p>${CFG.phone}</p><p>${CFG.inquiryEmail}</p><p>${CFG.website}</p></div><div><h4>PRODUCTS</h4><a href="corrugated.html">골판지 박스</a><a href="colorbox.html">종이 박스 / 칼라박스</a><a href="rigid.html">싸바리 박스</a><a href="other.html">기타</a></div><div><h4>COMPANY</h4><a href="portfolio.html">포트폴리오</a><a href="support.html">고객지원</a><a href="guide-structure.html">박스 구조 종류</a><a href="guide-process.html">제작 과정</a></div><div><h4>SERVICE</h4><a href="quote.html">견적문의</a><a href="guide-paper.html">종이 선택 가이드</a><a href="support.html#faq">자주 묻는 질문</a></div><div><h4>CONTACT</h4><p>상담 메일: ${CFG.inquiryEmail}</p><p>대표 전화: ${CFG.phone}</p><p>영업시간: 평일 09:00 - 18:00</p></div></div></footer>`);
}
function productCard(p){ return `<article class="product-card"><div class="badge-top">${p.tag||''}</div><img src="${p.img}" alt="${p.name}"><div class="body"><div class="product-meta"><strong>${p.name}</strong><span>${p.minQty||''}</span></div></div></article>`; }
