const cfg=window.SD_SITE_CONFIG||{};const db=window.SD_BOX_DB||[];
const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
function infoText(){return `${cfg.phone||''} · ${cfg.inquiryEmail||''}`;}
function renderDB(rows){qs('#dbTableBody').innerHTML=rows.map(r=>`<tr><td>${r.id}</td><td>${r.service}</td><td>${r.type}</td><td>${r.innerW}×${r.innerL}×${r.innerH}</td><td>${r.usage}</td><td>${r.minQty}</td><td>${r.material}</td></tr>`).join('');}
function score(box,service,usage,w,l,h,qty){if(box.service!==service)return-9999;if(box.innerW<w||box.innerL<l||box.innerH<h)return-9999;let s=0;const gap=(box.innerW-w)+(box.innerL-l)+(box.innerH-h);s+=Math.max(0,200-gap);if(usage&&box.usage.includes(usage))s+=80;if(Number(qty||0)>=box.minQty)s+=30;else s-=30;return s;}
function recommend(){const service=qs('#serviceType').value,usage=qs('#usageInput').value.trim(),w=+qs('#productW').value,l=+qs('#productL').value,h=+qs('#productH').value,qty=+qs('#productQty').value;if(!w||!l||!h){qs('#recommendList').innerHTML='<div class="empty">가로, 세로, 높이를 입력해 주세요.</div>';return;}const result=db.map(b=>({...b,score:score(b,service,usage,w,l,h,qty)})).filter(b=>b.score>-9999).sort((a,b)=>b.score-a.score).slice(0,5);if(!result.length){qs('#recommendList').innerHTML='<div class="empty">조건에 맞는 박스를 찾지 못했습니다.</div>';qs('#recommendedBoxSelect').innerHTML='<option>직접 상담 필요</option>';buildSummary();return;}qs('#recommendList').innerHTML=result.map(b=>`<article class="recommend-item"><img src="${b.sampleImage}" alt="${b.type}"><div><strong>${b.type}</strong><small>${b.service}</small><small>추천 규격: ${b.innerW}×${b.innerL}×${b.innerH}mm</small><small>용도: ${b.usage} · 최소수량 ${b.minQty}개</small><small>재질: ${b.material}</small></div></article>`).join('');qs('#recommendedBoxSelect').innerHTML=result.map(b=>`<option>${b.id} | ${b.type} | ${b.innerW}×${b.innerL}×${b.innerH}mm | ${b.material}</option>`).join('');buildSummary();}
function filterDB(){const f=qs('#dbServiceFilter').value,q=qs('#dbSearch').value.trim();let rows=db;if(f!=='전체')rows=rows.filter(r=>r.service===f);if(q)rows=rows.filter(r=>(r.type+' '+r.usage+' '+r.material).includes(q));renderDB(rows);}
function buildSummary(){qs('#selectionSummary').innerHTML=[`추천 박스: ${qs('#recommendedBoxSelect').value||'-'}`,`서비스: ${qs('#serviceType').value}`,`제품 크기: ${qs('#productW').value||'-'} × ${qs('#productL').value||'-'} × ${qs('#productH').value||'-'} mm`,`수량: ${qs('#productQty').value||'-'}`,`용도: ${qs('#usageInput').value||'-'}`].map(v=>`<div>${v}</div>`).join('');}
function submitForm(e){e.preventDefault();if(!cfg.formSubmitAction||cfg.formSubmitAction.includes('CHANGE_ME')){alert('config/site-config.js 에 inquiryEmail / formSubmitAction 을 먼저 넣어주세요.');return;}const form=e.currentTarget;['input[name="_subject"]','input[name="_captcha"]','textarea[name="selectionSummary"]'].forEach(sel=>{const old=form.querySelector(sel);if(old)old.remove();});let a=document.createElement('input');a.type='hidden';a.name='_subject';a.value=`[${cfg.companyName}] 자동추천 박스 문의`;let b=document.createElement('input');b.type='hidden';b.name='_captcha';b.value='false';let c=document.createElement('textarea');c.name='selectionSummary';c.style.display='none';c.value=qs('#selectionSummary').innerText+'\n\n추가 요청사항:\n'+(qs('#note').value||'없음');form.append(a,b,c);form.action=cfg.formSubmitAction;form.method='POST';form.submit();}
function openMail(){const body=encodeURIComponent(qs('#selectionSummary').innerText+'\n\n추가 요청사항:\n'+(qs('#note').value||'없음'));location.href=`mailto:${cfg.inquiryEmail}?subject=${encodeURIComponent('['+(cfg.companyName||'에스디컴퍼니')+'] 자동추천 박스 문의')}&body=${body}`;}
document.addEventListener('DOMContentLoaded',()=>{qs('#contactInfo').textContent=infoText();qs('#footerInfo').textContent=infoText();qs('#dbCount').textContent=`총 ${db.length}개`;renderDB(db);qs('#recommendBtn').addEventListener('click',recommend);qs('#dbServiceFilter').addEventListener('change',filterDB);qs('#dbSearch').addEventListener('input',filterDB);qsa('#recommend input, #recommend select').forEach(el=>el.addEventListener('input',buildSummary));qs('#quoteForm').addEventListener('submit',submitForm);qs('#openMailClientBtn').addEventListener('click',openMail);buildSummary();});
